# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WalmartLabs' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage', '~>3.8'
  pod 'SwiftyJSON'
  pod 'HCSStarRatingView', '~> 1.4.5'
  # Pods for WalmartLabs

end
